CC = gcc
CFLAGS = -pthread

all: s n client

s: StorageServerModule.c
	$(CC) $(CFLAGS) StorageServerModule.c -o s

n: NamingServerModule.c
	$(CC) $(CFLAGS) NamingServerModule.c -o n

client: clientfunctions.c
	$(CC) clientfunctions.c -o client

clean:
	rm -f s n client
